name: musafir
description: Musafir rental marketplace for tenants, house owners, and admins.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.6.1
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  supabase_flutter: ^2.5.0
  http: ^1.2.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
