#!/usr/bin/env python3
"""Dump the LIVE public schema as a REPLAYABLE baseline for a local Supabase.

`scripts/dump_live_schema.py` writes the reference snapshot (docs/live_schema.sql)
and says of itself "not guaranteed to replay cleanly". This one exists because
the migration chain in supabase/migrations does not apply from scratch — 003
declares `UNIQUE (LEAST(a,b), GREATEST(a,b))`, which Postgres has never
accepted, so live was built from SQL the repo does not hold (found 2026-09-18
by running `supabase start` for the first time). Until that chain is repaired,
a local or staging database can only come from live itself, and live can only
be read through the Management API (the SUPABASE_DB_URL "value" the secrets
API returns is a SHA-256, not a connection string).

Everything here is idempotent (`if not exists`, `or replace`, drop-then-create)
so tool/local_db_from_live.sh can apply the file repeatedly until the number
of failing statements stops shrinking — that is how dependency order between
functions, views and policies is resolved without a topological sort.

Output: supabase/baseline/live_baseline.sql (schema) and
        supabase/baseline/live_seed.sql   (reference rows: app_settings,
        facilities, landmarks; app_secrets KEYS only with placeholder values).
Never copies profiles, bookings, payments or any other user data.
"""
import json, os, re, subprocess, sys, urllib.request

REF = "bojkmonskqlhuakxhzcb"
TOKEN = subprocess.check_output(
    ["security", "find-generic-password", "-s", "Supabase CLI", "-w"]).decode().strip()
URL = f"https://api.supabase.com/v1/projects/{REF}/database/query"
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def q(sql):
    req = urllib.request.Request(
        URL, data=json.dumps({"query": sql}).encode(),
        headers={"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json",
                 "User-Agent": "curl/8.4.0"}, method="POST")
    try:
        with urllib.request.urlopen(req) as r:
            return json.loads(r.read())
    except urllib.error.HTTPError as e:
        print(f"QUERY FAILED (HTTP {e.code}):\n{sql[:300]}\n{e.read()[:400]}", file=sys.stderr)
        raise


NOT_EXT = "and not exists (select 1 from pg_depend d where d.objid={oid} and d.deptype='e')"
ROLES = ("anon", "authenticated", "service_role")
PRIV = {"a": "insert", "r": "select", "w": "update", "d": "delete", "D": "truncate",
        "x": "references", "t": "trigger", "X": "execute", "U": "usage"}

out = []
w = out.append


def acl_statements(acl, kind, name):
    """Turn a relacl/proacl into exact GRANTs for the three API roles + PUBLIC.
    `acl` None means owner-only. Anything an extension owns is skipped upstream."""
    stmts = [f"revoke all on {kind} {name} from public, {', '.join(ROLES)};"]
    if not acl:
        return stmts
    for entry in acl.strip("{}").split(","):
        if not entry:
            continue
        grantee, rest = entry.split("=", 1)
        letters = rest.split("/", 1)[0]
        grantee = grantee.strip('"') or "public"
        if grantee not in ROLES and grantee != "public":
            continue  # postgres / supabase_admin own their grants already
        privs = sorted({PRIV[c] for c in letters if c in PRIV})
        if privs:
            stmts.append(f"grant {', '.join(privs)} on {kind} {name} to {grantee};")
    return stmts


w("-- Generated by tool/dump_live_baseline.py from the LIVE catalog. Do not edit;")
w("-- regenerate. Replayable + idempotent: apply repeatedly until stable.")
w("set check_function_bodies = off;")
w("")

# ---- EXTENSIONS ----
w("-- ===== extensions =====")
for e in q("select extname from pg_extension where extname not in ('plpgsql','supabase_vault','pg_stat_statements','pg_graphql','pgsodium') order by 1"):
    schema = "extensions" if e["extname"] not in ("postgis",) else "public"
    # 001 put postgis in public (CLAUDE.md: its tables are exposed there); keep that.
    w(f"create extension if not exists \"{e['extname']}\"" + (f" with schema {schema}" if schema == "public" else "") + ";")
w("")

# ---- ENUMS ----
w("-- ===== enum types =====")
enums = q(f"""select t.typname as name, t.oid,
  array_agg(quote_literal(e.enumlabel) order by e.enumsortorder) as labels
from pg_type t join pg_enum e on e.enumtypid=t.oid
join pg_namespace n on n.oid=t.typnamespace where n.nspname='public'
  {NOT_EXT.format(oid='t.oid')}
group by t.typname, t.oid order by t.typname""")
for e in enums:
    w(f"do $e$ begin if not exists (select 1 from pg_type where typname='{e['name']}' and typnamespace='public'::regnamespace) then")
    w(f"  create type public.{e['name']} as enum ({', '.join(e['labels'])}); end if; end $e$;")
w("")

# ---- SEQUENCES ----
w("-- ===== sequences =====")
seqs = q("select sequencename, sequenceowner from pg_sequences where schemaname='public'")
for s in seqs:
    w(f"create sequence if not exists public.{s['sequencename']};")
w("")

# ---- TABLES ----
tables = [r["table_name"] for r in q(f"""select c.relname as table_name from pg_class c
 join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r'
 {NOT_EXT.format(oid='c.oid')} order by c.relname""")]
cols = q("""select table_name, column_name, ordinal_position,
  case when data_type in ('USER-DEFINED','ARRAY') then udt_name else data_type end as type,
  data_type, is_nullable, column_default, character_maximum_length,
  is_generated, generation_expression, is_identity
from information_schema.columns where table_schema='public' order by table_name, ordinal_position""")
by_tbl = {}
for c in cols:
    by_tbl.setdefault(c["table_name"], []).append(c)
# geography/geometry columns carry their typmod (srid) in format_type, not udt_name
fmt = {(r["tbl"], r["col"]): r["ft"] for r in q("""select c.relname tbl, a.attname col,
  format_type(a.atttypid, a.atttypmod) ft from pg_attribute a join pg_class c on c.oid=a.attrelid
  join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r'
  and a.attnum>0 and not a.attisdropped""")}
cons = q("""select conrelid::regclass::text as tbl, conname, pg_get_constraintdef(oid) as def, contype
from pg_constraint where connamespace='public'::regnamespace and contype <> 't'
order by conrelid::regclass::text, contype desc, conname""")
cons_by_tbl, fks = {}, []
for c in cons:
    if c["contype"] == "f":
        fks.append(c)
    else:
        cons_by_tbl.setdefault(c["tbl"], []).append(c)

w("-- ===== tables (foreign keys deferred to the end of this section) =====")
for t in tables:
    lines = []
    for c in by_tbl.get(t, []):
        typ = fmt.get((t, c["column_name"]), c["type"])
        if c["data_type"] == "ARRAY" and not typ.endswith("[]"):
            typ = c["type"].lstrip("_") + "[]"
        seg = f"  {c['column_name']} {typ}"
        if c["is_generated"] == "ALWAYS" and c["generation_expression"]:
            seg += f" generated always as ({c['generation_expression']}) stored"
        elif c["is_identity"] == "YES":
            seg += " generated by default as identity"
        elif c["column_default"] is not None:
            seg += f" default {c['column_default']}"
        if c["is_nullable"] == "NO":
            seg += " not null"
        lines.append(seg)
    w(f"create table if not exists public.{t} (\n" + ",\n".join(lines) + "\n);")
    for c in cons_by_tbl.get(f"public.{t}", []) + cons_by_tbl.get(t, []):
        w(f"do $c$ begin if not exists (select 1 from pg_constraint where conname='{c['conname']}' and conrelid='public.{t}'::regclass) then")
        w(f"  alter table public.{t} add constraint {c['conname']} {c['def']}; end if; end $c$;")
w("")
w("-- ===== foreign keys =====")
for c in fks:
    tbl = c["tbl"] if "." in c["tbl"] else f"public.{c['tbl']}"
    w(f"do $c$ begin if not exists (select 1 from pg_constraint where conname='{c['conname']}' and conrelid='{tbl}'::regclass) then")
    w(f"  alter table {tbl} add constraint {c['conname']} {c['def']}; end if; end $c$;")
w("")

# ---- FUNCTIONS ----
w("-- ===== functions =====")
fns = q(f"""select p.proname, p.oid, pg_get_functiondef(p.oid) as def, p.proacl::text as acl,
  pg_get_function_identity_arguments(p.oid) as args
from pg_proc p join pg_namespace n on n.oid=p.pronamespace
where n.nspname='public' and p.prokind in ('f','p') {NOT_EXT.format(oid='p.oid')}
order by p.proname, p.oid""")
for f in fns:
    w(f["def"].rstrip() + ";\n")

# ---- VIEWS ----
w("-- ===== views =====")
views = q(f"""select c.relname as name, pg_get_viewdef(c.oid, true) as def,
  array_to_string(c.reloptions, ', ') as opts, c.relacl::text as acl
from pg_class c join pg_namespace n on n.oid=c.relnamespace
where n.nspname='public' and c.relkind='v' {NOT_EXT.format(oid='c.oid')} order by c.relname""")
for v in views:
    opts = f" with ({v['opts']})" if v["opts"] else ""
    w(f"create or replace view public.{v['name']}{opts} as\n{v['def']}")
w("")

# ---- INDEXES ----
w("-- ===== indexes =====")
idx = q("""select tablename, indexname, indexdef from pg_indexes where schemaname='public'
  and indexname not in (select conname from pg_constraint where connamespace='public'::regnamespace)
order by tablename, indexname""")
idx = [i for i in idx if i["tablename"] in tables]
for i in idx:
    w(re.sub(r"^CREATE (UNIQUE )?INDEX ", lambda m: f"CREATE {m.group(1) or ''}INDEX IF NOT EXISTS ", i["indexdef"]) + ";")
w("")

# ---- RLS + POLICIES ----
w("-- ===== row level security =====")
rls = q("select c.relname t, c.relforcerowsecurity f from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and c.relrowsecurity order by 1")
for r in rls:
    w(f"alter table public.{r['t']} enable row level security;" + (f" alter table public.{r['t']} force row level security;" if r["f"] else ""))
pols = q("""select tablename, policyname, permissive, cmd, roles::text as roles, qual, with_check
from pg_policies where schemaname='public' order by tablename, policyname""")
for p in pols:
    roles = p["roles"].strip("{}").replace(",", ", ")
    parts = [f'drop policy if exists "{p["policyname"]}" on public.{p["tablename"]};',
             f'create policy "{p["policyname"]}" on public.{p["tablename"]}',
             f"  as {p['permissive'].lower()} for {p['cmd'].lower()} to {roles}"]
    if p["qual"] is not None:
        parts.append(f"  using ({p['qual']})")
    if p["with_check"] is not None:
        parts.append(f"  with check ({p['with_check']})")
    w("\n".join(parts) + ";")
w("")

# ---- TRIGGERS (public + the auth.users hook) ----
w("-- ===== triggers =====")
trg = q("""select n.nspname sch, c.relname tbl, t.tgname, pg_get_triggerdef(t.oid) as def
from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace
join pg_proc p on p.oid=t.tgfoid join pg_namespace pn on pn.oid=p.pronamespace
where not t.tgisinternal and (n.nspname='public' or (n.nspname='auth' and pn.nspname='public'))
order by n.nspname, c.relname, t.tgname""")
# Create-if-absent rather than drop-and-create: `postgres` holds TRIGGER on
# spatial_ref_sys (owned by supabase_admin) and can CREATE a trigger there but
# cannot DROP one — 115's whole point — so a drop would fail every re-run.
for t in trg:
    w(f"do $t$ begin if not exists (select 1 from pg_trigger x join pg_class c on c.oid=x.tgrelid"
      f" join pg_namespace n on n.oid=c.relnamespace where x.tgname='{t['tgname']}' and c.relname='{t['tbl']}'"
      f" and n.nspname='{t['sch']}') then execute $q$ {t['def']} $q$; end if; end $t$;")
w("")

# ---- GRANTS ----
w("-- ===== grants (exact, replacing the default-privilege accident) =====")
rels = q(f"""select c.relname, c.relkind, c.relacl::text acl from pg_class c
 join pg_namespace n on n.oid=c.relnamespace where n.nspname='public'
 and c.relkind in ('r','v','S') {NOT_EXT.format(oid='c.oid')} order by c.relkind, c.relname""")
for r in rels:
    kind = "sequence" if r["relkind"] == "S" else "table"
    for s in acl_statements(r["acl"], kind, f"public.{r['relname']}"):
        w(s)
colg = q("""select cp.table_name, cp.grantee, cp.privilege_type,
  array_agg(cp.column_name order by cp.column_name) cols
from information_schema.column_privileges cp where cp.table_schema='public'
  and cp.grantee in ('anon','authenticated','service_role')
group by 1,2,3
having count(*) <> (select count(*) from information_schema.columns c
                    where c.table_schema='public' and c.table_name=cp.table_name)""")
for g in colg:
    cols = g["cols"] if isinstance(g["cols"], list) else g["cols"].strip("{}").split(",")
    w(f"grant {g['privilege_type'].lower()} ({', '.join(cols)}) on public.{g['table_name']} to {g['grantee']};")
for f in fns:
    for s in acl_statements(f["acl"], "function", f"public.{f['proname']}({f['args']})"):
        w(s)
w("")

# ---- STORAGE (buckets + their policies) ----
# The app's images live here: listing-images, avatars and chat-attachments are
# public buckets, documents (identity proof) is private. Without these a local
# mirror silently accepts every upload, which is the opposite of the live rule.
w("-- ===== storage buckets =====")
for b in q("select id, public, file_size_limit, allowed_mime_types::text as mimes from storage.buckets order by id"):
    mimes = "null" if not b["mimes"] else "'" + b["mimes"] + "'::text[]"
    lim = b["file_size_limit"] if b["file_size_limit"] is not None else "null"
    w(f"insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)"
      f" values ('{b['id']}', '{b['id']}', {str(b['public']).lower()}, {lim}, {mimes})"
      f" on conflict (id) do update set public = excluded.public,"
      f" file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;")
w("")
w("-- ===== storage policies =====")
for p_ in q("""select policyname, permissive, cmd, roles::text as roles, qual, with_check
from pg_policies where schemaname='storage' and tablename='objects' order by policyname"""):
    roles = p_["roles"].strip("{}").replace(",", ", ")
    parts = [f'drop policy if exists "{p_["policyname"]}" on storage.objects;',
             f'create policy "{p_["policyname"]}" on storage.objects',
             f"  as {p_['permissive'].lower()} for {p_['cmd'].lower()} to {roles}"]
    if p_["qual"] is not None:
        parts.append(f"  using ({p_['qual']})")
    if p_["with_check"] is not None:
        parts.append(f"  with check ({p_['with_check']})")
    w("\n".join(parts) + ";")
w("")

# ---- CRON ----
w("-- ===== pg_cron jobs =====")
for j in q("select jobname, schedule, command from cron.job order by jobname"):
    cmd = j["command"].replace("'", "''")
    w(f"select cron.unschedule('{j['jobname']}') where exists (select 1 from cron.job where jobname='{j['jobname']}');")
    w(f"select cron.schedule('{j['jobname']}', '{j['schedule']}', '{cmd}');")
w("")

os.makedirs(os.path.join(REPO, "supabase", "baseline"), exist_ok=True)
with open(os.path.join(REPO, "supabase", "baseline", "live_baseline.sql"), "w") as fh:
    fh.write("\n".join(out) + "\n")

# ---- SEED: reference rows only ----
seed = ["-- Reference rows from live. No user data. app_secrets keys only."]
for t in ("app_settings", "facilities", "landmarks"):
    rows = q(f"select json_agg(t) j from public.{t} t")[0]["j"] or []
    js = json.dumps(rows).replace("'", "''")
    seed.append(f"insert into public.{t} select * from json_populate_recordset(null::public.{t}, '{js}') on conflict do nothing;")
keys = [r["key"] for r in q("select key from public.app_secrets order by key")]
for k in keys:
    seed.append(f"insert into public.app_secrets (key, value) values ('{k}', 'local-placeholder') on conflict (key) do nothing;")
with open(os.path.join(REPO, "supabase", "baseline", "live_seed.sql"), "w") as fh:
    fh.write("\n".join(seed) + "\n")

print(f"baseline: enums={len(enums)} tables={len(tables)} fks={len(fks)} functions={len(fns)} "
      f"views={len(views)} indexes={len(idx)} policies={len(pols)} triggers={len(trg)} grants_rel={len(rels)}")
